<a href="https://colab.research.google.com/github/Hyewon97/python_demo/blob/main/p200_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Numpy
- NumPy는 Numerical Python의 줄임말로, 파이썬에서 산술 계산을 위한 가장 필수 패키지중 하나이다.
- 과학 계산을 위한 대부분의 패키지는 NumPy의 배열 객체를 데이터 교환을 위한 공통 언어처럼 사용한다.
- 효율적인 다차원 배열인 ndarray(n dimensional array)는 빠른 배열 계산과 유연한 브로드캐스팅 기능을 제공한다.
- 반복문을 작성할 필요 없이 전체 데이터 배열을 빠르게 계산할 수 있는 표준 수학 함수이다.
- 배열 데이터를 디스크에 쓰거나 읽을 수 있는 도구와 메모리에 적재된 파일을 다루는 도구이다.
- 선형대수, 난수 생성기등에 사용된다.
- C, C++, 포트란으로 작성한 코드를 연결할 수 있는 C API가 제공된다.

공식문서 https://numpy.org/doc/stable/   
numpy 100 문제 https://github.com/rougier/numpy-100


## 1. 데이터 생성

In [ ]:
# !pip install numpy
import numpy as np

In [ ]:
# 배열의 자원을 생성하기
a = np.zeros(3) # 3개의 0 값을 갖는 1차원 배열 - 벡터

In [ ]:
a

array([0., 0., 0.])

In [ ]:
# 처음 객체들은 type(), dir()을 해본다.
print(type(a))
print(dir(a))

<class 'numpy.ndarray'>
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__r

In [ ]:
# 1 차원 배열 = 벡터
a = np.array([1,2,3]) # 리스트 값을 줘서 배열을 생성 가능하다.
a

array([1, 2, 3])

In [ ]:
print(type(a))
print(dir(a))
print(len(dir(a)))

<class 'numpy.ndarray'>
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__r

In [ ]:
# 2차원 배열 = 행렬, 리스트를 다른 리스트로 감싸는 형태인듯
b =np.array([[1,2], [3,4]])
b

array([[1, 2],
       [3, 4]])

In [ ]:
# 3차원 배열 이상 = 텐서(tensor)
c = np.array([[[1,2],[3,4]],
            [[5,6],[7,8]]])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
# 문자 데이터가 하나라도 있으면 전체가 문자로 바뀐다.
# numpy는 homogeneous이다.
a = np.array([1,'2', 3])
print(a)
print(type(a))
print(type(a[0]))

['1' '2' '3']
<class 'numpy.ndarray'>
<class 'numpy.str_'>


In [ ]:
b = np.array(['a', 1, True])
print(b)
print(type(b))
b

['a' '1' 'True']
<class 'numpy.ndarray'>


array(['a', '1', 'True'], dtype='<U21')

In [ ]:
c = np.array([1, True, 2, False])
print(c)
print(type(c))
c
print(type(c[0]))

[1 1 2 0]
<class 'numpy.ndarray'>
<class 'numpy.int64'>


### np.zeros
- tupe로 인자를 넣으면 그대로 모양을 만든다.
- (2,3) : 2행 3열 행렬을 만든다.
- zeros는 기본값으로 0.으로 값을 모두 채운다.  
a=np.zeros([2,3])  
a=np.zeros((2,3))

In [ ]:
a = np.zeros([2,3])
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a = np.zeros([2,3,4]) # 갯수, 행, 열
a

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

### np.eye
- eye는 단위 행렬
- 숫자만 사용할 수 있다.

In [ ]:
# 인자값 1개이면 행과 열이 같다.
# 3행 3열 행렬을 생성한다.
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# eye은 행과 열의 크기를 지정할 수 있다.
# 3행 2열 행렬생성
a = np.eye(3,2)
a

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [ ]:
# 크기(1)가 시작되는 위치를 지정할 수 있다.
c = np.eye(3,4,k=1)
c

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### np.identity
- 수학에서 단위행렬을 영어로 indentity matrix
- 크기 한 개만 지정해서 생성할 수 있다.

In [ ]:
a = np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# 크기 2개를 지정하는 경우 오류가 발생한다.
# TypeError
# 인자 하나만 지정할 수 있다.
a = np.identity(3,2)
a

TypeError: ignored

### np.full
- 지정한 크기의 배열을 생성하고 채울값을 지정한다.
- 2행 2열의 배열 생성 후 1로 채워준다.  


  np.full((2,2),1)

In [ ]:
a=  np.full((2,2),1) # 2행 2열이 생성되고 1로 데이터 값이 채워진다.
a

array([[1, 1],
       [1, 1]])

In [ ]:
b = np.full(3,4) # 4로 채운다 1행 3열을
b

array([4, 4, 4])

In [ ]:
c = np.full((2,2),[1,2]) # 1, 2 값이 반복된다.
c

array([[1, 2],
       [1, 2]])

In [ ]:
d = np.full((2,2),[[1,2],[3,4]])
d

array([[1, 2],
       [3, 4]])

### np.empty
- 배열을 생성하고 초기화를 지정하지 않는다.
- 메모리에 있는 값이나 이전에 사용했던 값들로 채워진다.

In [ ]:
a = np.empty(3) # 딱히 값이 보전되지 않는듯
a

array([0.00000000e+000, 0.00000000e+000, 6.93178475e-310])

In [ ]:
k = np.zeros((2,3))
k

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# zeros해서 생성한 배열이 있으면 배열의 값을 0으로 채워준다.
b = np.empty((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
c = np.empty((2,5))
c

array([[1.91436999e-316, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [6.17885692e-042, 1.14195471e-071, 7.79295647e-091,
        4.31243442e-033, 8.07217623e-315]])

### np.ones
- 배열의 모든 값을 1로 채운다

In [ ]:
# 1행 3열의 배열 생성 후 모든 값을 1로 채운다.
a = np.ones(3)
a

array([1., 1., 1.])

In [ ]:
# b = np.ones([2,3])
b=np.ones((2,3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

### _like
- _like가 붙으면 shpae이 같게 만들어진다.
- 연산하기 위해서 shpae을 맞춰야 하는 경우가 있다.

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.shape

(2, 3)

In [ ]:
b=np.empty_like(a) # 안에 있는 값을 생성할 때는 2행 3열에 맞게 생성이 된다. a와 같은 행렬 사이즈
b

array([[4607182418800017408, 4607182418800017408, 4607182418800017408],
       [4607182418800017408, 4607182418800017408, 4607182418800017408]])

In [ ]:
c = np.eye(2)
c

array([[1., 0.],
       [0., 1.]])

In [ ]:
c.shape

(2, 2)

In [ ]:
d = np.eye(3)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
d.shape

(3, 3)

In [ ]:
# 행렬 사이즈가 맞지 않아서 계산 불가
# ValueError
c + d

ValueError: ignored

### linespace
- 동등한 간격으로 값을 생성한다.
- 0부터 49까지 50개 생성된다면 세번째 num인자 값이 생략되어 있음으로 start와 end 계산해서 default 50이 생성된다.  
- linespace(start, end ,num)
- linespace(0,49) #num=50

In [ ]:
a = np.linspace(0, 49)
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.])

In [ ]:
b = np.linspace(0, 20)
b

array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ])

In [ ]:
len(b)

50

In [ ]:
# 1부터 10까지 3개의 요서를 생성한다.
# 기본은 endpoint=True로 설정되어 있기 때문에 10이 포함이 된다.
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [ ]:
# 1부터 10까지 3개의 요서를 생성한다.
# 기본은 endpoint=False로 설정되어 있기 때문에 10이 포함이 안된다.
np.linspace(1,10,3, endpoint=False) # endpoint를 f로 하면 마지막(10) 값을 포함하지 않고 3등분을 한다.

array([1., 4., 7.])

### longspace
- linespace와 비슷하다
- long scale을 사용하는 차이가 있다.
- 1부터 50까지 사이의 10개의 요소를 생성한다.
- np.logspace(1, 50, 10)

In [ ]:
a = np.logspace(1, 50, 10)
a

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

### dtype
- numpysms c언어를 기반으로 해서 만들었기 때문에 c의 데이터 타입을 차용할 수 있다.

In [ ]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
print(type(a))
print(a.dtype)

<class 'numpy.ndarray'>
int64


In [ ]:
b= np.array([1,2,3], dtype=np.int8)
b

array([1, 2, 3], dtype=int8)

In [ ]:
# np.int8은 -128 ~127 사이의 값을 지정할 수 있다.
c = np.array([-127, -128, 17, 2, 3, -127, -128, 127], dtype=np.int8)
c

array([-127, -128,   17,    2,    3, -127, -128,  127], dtype=int8)

In [ ]:
# int는 python의 int을 사용한다.
d = np.array([127,2,3,-127,-128], dtype=int)
d

array([ 127,    2,    3, -127, -128])

In [ ]:
type(d[0]) # 내부적으로 기본 64비트로 처리가 된다.

numpy.int64

## python 도움

In [ ]:
?sum # 도움말 출력

In [ ]:
help(sum)

Help on built-in function sum in module builtins:

sum(iterable, /, start=0)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers
    
    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.



## numpy 도움말

In [ ]:
np.lookfor('sum')

Search results for 'sum'
------------------------
numpy.sum
    Sum of array elements over a given axis.
numpy.cumsum
    Return the cumulative sum of the elements along a given axis.
numpy.einsum
    einsum(subscripts, *operands, out=None, dtype=None, order='K',
numpy.nansum
    Return the sum of array elements over a given axis treating Not a
numpy.nancumsum
    Return the cumulative sum of array elements over a given axis treating Not a
numpy.einsum_path
    Evaluates the lowest cost contraction order for an einsum expression by
numpy.trace
    Return the sum along diagonals of the array.
numpy.ma.sum
    Return the sum of the array elements over the given axis.
numpy.Bytes0.sum
    Scalar method identical to the corresponding array attribute.
numpy.polyadd
    Find the sum of two polynomials.
numpy.ma.cumsum
    Return the cumulative sum of the array elements over the given axis.
numpy.logaddexp
    Logarithm of the sum of exponentiations of the inputs.
numpy.Bytes0.cumsum
    Scal

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# array이 몇 차원인지 알려준다.
# shpae로도 알 수 있다.
a.ndim # 몇 차원인지 출력

2

In [ ]:
# 데이터 타입을 알려준다.
a.dtype

dtype('int64')

In [ ]:
# 요소의 개수를 알려준다.
# shape로도 알 수 있다.
a.size


6

In [ ]:
# 요소당 byte수를 알려준다.
a.itemsize

8

### numpy와 python의 속도 차이

In [ ]:
np.arange(10) # range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# numpy을 이용한 계산
%time np.sum(np.arange(1000000000))

CPU times: user 1.73 s, sys: 2.96 s, total: 4.69 s
Wall time: 4.71 s


499999999500000000

In [ ]:
%time sum(range(1000000000))

CPU times: user 19.8 s, sys: 0 ns, total: 19.8 s
Wall time: 19.8 s


499999999500000000

같은 np.sum() 사용하더라도 값을 생성하는 방법에 따라 속도가 달라진다.

In [ ]:
import numpy as np
%time np.sum(range(10000)) # 원래 0이 9개여야 하는데 서버가 다운된다고....^^

CPU times: user 4.5 ms, sys: 858 µs, total: 5.36 ms
Wall time: 12.9 ms


49995000

### copy
※ 대입문 6가지  
a = 1  
a = b = 1  
a, b =1,2  
a, *b = 1, 2, 3  
a += 1  
global, nonlocal  

### python copy

In [ ]:
a = [1,2,3] #sequence, mutable, heterogeneous

In [ ]:
b = a

In [ ]:
b

[1, 2, 3]

In [ ]:
a is b # 메모리 주소 비교

True

In [ ]:
# a와 b가 메모리 주소를 공유
# b값을 변경하면 a도 같이 변경이 된다.
b[0] = 7

In [ ]:
b

[7, 2, 3]

In [ ]:
a # a값도 같이 변경이 되어 있다. 왜??

[7, 2, 3]

### list copy()

In [ ]:
a = [1, 2, 3]

In [ ]:
# copy( )는 똑같은 값만 가지고 메모리는 공유하지 않는다.
b = a.copy()

In [ ]:
a is b # 메모리 주소

False

In [ ]:
id(a)

140062602006848

In [ ]:
id(b)

140062601473152

In [ ]:
b[0] = 8

In [ ]:
b

[8, 2, 3]

In [ ]:
a

[1, 2, 3]

In [ ]:
print(a is b)
print(a==b)

False
False


list가 2차원일  때


In [ ]:
a =[[1,2,3]]

In [ ]:
type(a)

list

In [ ]:
b=a.copy()

In [ ]:
# shallow copy,, 얇은 복사
print(a is b)
print(a==b)

False
True


In [ ]:
print(a[0] is b[0])
print(a[0]==b[0])

True
True


### list deepcopy()

In [ ]:
import copy

In [ ]:
a=[[1,2,3]]
b=copy.deepcopy(a)

In [ ]:
print(a)
print(b)

[[1, 2, 3]]
[[1, 2, 3]]


In [ ]:
print(a is b)
print(a==b)
print(a[0] is b[0]) # deep copy가 됨, 2차원 배열은 주소가 복사 되는 듯?
print(a[0] == b[0])

False
True
False
True


[:]는 전체라는 뜻이다.  
슬라이싱 방식으로 1차 리스트일때는 재할당하면 deppcopy가 된다.  
슬라이싱 2차 리스트 이상인 경우 shallow copy가 발생한다.

In [ ]:
a=[1,2,3]
# 슬라이싱 1차원 배열
b = a[:]
print(a is b)
print(a == b)
b[0]=7
print(a is b)
print(a==b) # 값이 다름.. deep copy가 됨(1차원 배열이여서)

False
True
False
False


In [ ]:
a=[[1,2,3]]
# 슬라이싱 2차 이상인 경우 shallow copy가 된다.
b = a[:]
print(a is b)
print(a == b)
b[0][0]=7
print(a is b)
print(a==b)

False
True
False
True


※ python의 copy는 기본적으로 2차원부터 shallow copy을 한다.  

### numpy의 copy

In [ ]:
import numpy as np
a = b =np.array([1,2,3])

In [ ]:
print(a is b)
print(a==b)

True
[ True  True  True]


array는 sequence 타입으로 인덱싱과 슬라이싱이 가능하다.

In [ ]:
a[0] # indexing

1

In [ ]:
a[:] # slicing

array([1, 2, 3])

In [ ]:
# array는 mutable이다.
# 예와가 몇 가지 있지만 mutable에 가깝다.
a[0] = 100
print(a)
print(b)

[100   2   3]
[100   2   3]


array는 homogeneous, sequence, mutable이다  

array deepcopy

In [ ]:
a = np.array([[1,2,3]])
# numpy는 기본적으로 deepcopy이다.
b=a.copy()

In [ ]:
print(a is b)

False


### as 계열
다른 데이터 타입을 가져와서 바꿔서 사용할 때는 as라는 이름이 보통 붙는다.   

In [ ]:
# python의 list 데이터 타입을 int ndarray로 변환
a = [1,2,3] # python의 list
print(type(a))
print(type(a[0]))

b = np.array(a) # numpy의 array
print(type(b))
print(type(b[0])) # int 변수

<class 'list'>
<class 'int'>
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [ ]:
# python의 list 데이터 타입을 int ndarray로 변환
a = [1,2,3] # python의 list
print(type(a))
print(type(a[0]))

b = np.asfarray(a) # numpy의 array
print(type(b))
print(type(b[0])) # 실수로 변경됨

<class 'list'>
<class 'int'>
<class 'numpy.ndarray'>
<class 'numpy.float64'>


In [ ]:
# python의 list 데이터 타입을 int ndarray로 변환
a = [1.,2.,3.] # 실수 리스트 선언
print(type(a))
print(type(a[0]))

b = np.asarray(a) # numpy의 array
print(type(b))
print(type(b[0])) # 실수형 그대로 가지고 옴

<class 'list'>
<class 'float'>
<class 'numpy.ndarray'>
<class 'numpy.float64'>


### 배열의 값 가져오

#### (1) comma로 값 가져오

In [ ]:
a = [[1,2,3],[4,5,6]] # python
b = np.array([[1,2,3],[4,5,6]]) # array

In [ ]:
a[0]

[1, 2, 3]

In [ ]:
a[0,1]

TypeError: ignored

In [ ]:
# 특정한 위치를 가지고 올 때는 행렬을 구분해서 인덱스 값을 적는다.
a[0][1]

2

In [ ]:
a[slice(0,1)]

[[1, 2, 3]]

In [ ]:
b[0]

array([1, 2, 3])

In [ ]:
b[0,1]

2

#### (2) boolean indexing

In [ ]:
a = [[1,2,3,4]] # python list

In [ ]:
# TypeError
a > 3

TypeError: ignored

In [ ]:
b = np.array([1,2,3,4])
b  

array([1, 2, 3, 4])

In [ ]:
b > 3 # 배열 하나씩 비교해서 값을 비교해준다.

array([False, False, False,  True])

arry를 scalar와 연산하면 elementwise로 계산한다.  
(elementwise : 원소별로 각각 계산이 된다.)  

In [ ]:
b[b>3] # True인 값만 가져온다

array([4])

### numpy에서 boolean indexing 조건
- array만 가능하다.
- numpy True, Flase로만 가능하다.
- shpae이 맞아야 한다.(개수가 맞을때만 사용할 수 있다.)

####(3) fancy indexing

In [ ]:
b = np.arange(100).reshape([20,5]) # reshpae(행,열) 배열의 구조 변경
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [ ]:
b[:] # b의 전체를 가져온다. b[:,:]와 같다
print(b[1])
print(' ')
print(b[1:3]) # 1행에서부터 3 미만의 행의 값을 가지고 와라.
print(' ')
print(b[1:3,2:4]) # 행렬 자리의 슬라이싱 기법을 사용해서 넣어준다. 1행에서부터3열미만, 2열부터 4열 미만의 값을 가지고 와라
print(' ')
print(b[[1, 3, 5]])
print(' ')
print(b[[1, 3, 5],[0,2,4]])
print(' ')
#print(b[:,[0,2,4]]) # 모든 행을 가지고 오면서 0,2,4열?에 해당되는 데이터만 가지고 오기

[5 6 7 8 9]
 
[[ 5  6  7  8  9]
 [10 11 12 13 14]]
 
[[ 7  8]
 [12 13]]
 
[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [25 26 27 28 29]]
 
[ 5 17 29]
 


In [ ]:
# fancying indexing은 인덱싱 기법만 사용할 수 있다.
# ":" (콜론)은 슬라이싱 기법이므로 지원하지 않는다.
b[[2:5]]

SyntaxError: ignored

fancy indexing은 개수가 같게 지정되어야 한다.

In [ ]:
# 정상처리
b[[1,3,4],[0,2,1]] # 1번째 행 0번째 열, 3번째 행 2번째 열, 4번째 행 1번째 열

array([ 5, 17, 21])

In [ ]:
b[[1,3,4],[0,2]] # IndexError가 발생한다.

IndexError: ignored

In [ ]:
### 3차원 이상에서 차원 구붑법

In [ ]:
b = np.arange(24).reshape(2,3,4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
b[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
b[0, 1]

array([4, 5, 6, 7])

In [ ]:
b[0,1,3]

7

### fancy indexing와 indexing 차이
- indexing은 원래 차원에서 하나 감소해서 가져오고 fancy indexing은 원래 차원 그대로 가져온다.   

In [ ]:
b[0] # indexing은 차원이 하나 감소해서 가져온다. (3차원 2차원으로 가져옴)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b[[0]] #fancy indexing은 원래 3차원 그대로 가져온다.

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [ ]:
b[0]
b[0,:,:]
# b[[0.:.]] # fancy indexing에서는 사용 못함
b[[0],:,:] # 0번째에 있는 데이터를 가져오고 한번 더 끊어줘야 한다... 원래 형태 그대로 가져와야 할 때 적용하면 됨.

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

### Ellipsis

In [ ]:
b[0,:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b[0,...] # 쉼표 하나, 점 3개

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
type(...)

ellipsis

In [ ]:
b[0] # 생략기법(인덱싱 기법)
b[0,:,:] # 슬라이싱 기법
b[0,...] # Ellipse 기법

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
# 숫자 1, 5, 9만 가져온다.
b[0,:,1]

array([1, 5, 9])

In [ ]:
# 숫자 1,5,9,3,7,11 가져오기
b[[0],:,[1,3]]

array([[ 1,  5,  9],
       [ 3,  7, 11]])

In [ ]:
# 숫자 4,5,6,7,16,17,18,29 가져오기
b[:,1,:]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [ ]:
b[:,1:2,:]

array([[[ 4,  5,  6,  7]],

       [[16, 17, 18, 19]]])

현재 몇차원인데 결과는 몇차원인지 비교를 해가면서 해야한다.

In [ ]:
# 3,7,11,15,19,23 가져오기
#b[:,:,3] # 차원이 달라져서 가지고 온다. 아마 2차배열로 가지고 오는 것 같음
b[:,:,[3]] # 원래값, 3차원으로 가져온다.

array([[[ 3],
        [ 7],
        [11]],

       [[15],
        [19],
        [23]]])

### 줄임표현(...)
출력해야할 데이터 수가 엄청 클 때 보이는 ...은 Ellipsis와 다르다.

In [ ]:
# out에 나오는 ...은 단순히 줄임표현이다.
np.arange(100000)

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [ ]:
np.set_printoptions(edgeitems=6)

In [ ]:
np.arange(100000) # 6개씩 출력이 된다. 디폴트는 3개인듯

array([    0,     1,     2,     3,     4,     5, ..., 99994, 99995, 99996,
       99997, 99998, 99999])

### 연산
numpy 연산의 기본은 두 개의 shape이 같아야 한다.

In [ ]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a.shape

(3, 4)

In [ ]:
b = np.arange(1,13).reshape(3,4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b.shape

(3, 4)

numpy는 elementwise로 vectorize 연산을 한다.   
vectorize는 데이터의 연산을 일괄적으로 처리하는 기능이다.   

In [ ]:
# 같은 위치의 요소끼리 더해준다.(elementwise)
a+b # 자리에 맞는 데이터끼리 연산이 된다.

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [ ]:
[1,2,3] + [4,5,6] #python list

[1, 2, 3, 4, 5, 6]

numpy는 python함수도 vectorize 시키는 기능을 지원한다.

In [ ]:
@np.vectorize
def plus(a,b):
  return a+b

plus([1,2,3],[4,5,6])

array([5, 7, 9])

In [ ]:
a*b

array([[  0,   2,   6,  12],
       [ 20,  30,  42,  56],
       [ 72,  90, 110, 132]])

In [ ]:
# 오류가 발생된다.
[1,2,3] * [4,5,6]

TypeError: ignored

행렬곱을 하기 위해서 매트릭스가 제공된다.  
딥러닝 훈련시킬 때 실제로 적용이 되는 기술이다.  


In [ ]:
c = np.matrix([[1,2],[3,4]])
c

matrix([[1, 2],
        [3, 4]])

In [ ]:
type(c)

numpy.matrix

In [ ]:
c*c

matrix([[ 7, 10],
        [15, 22]])

In [ ]:
import numpy as np

In [ ]:
a = np.arange(12).reshape(3,4)
print(a)
print(a.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [ ]:
b = np.arange(1,13).reshape(3,4)
print(b)
print(b.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


ndarry에서 행렬곱 연산자 @이다.  
python 재단에서 numpy를 위해 만들어준 연산자이다.

In [ ]:
# 오류 발생.. 쉐이프가 맞지 않음
a@b

ValueError: ignored

행렬곱을 하기 위해서는 shpae가 맞아야 한다.  
T는 transpose(전치)의 약자이다.

In [ ]:
b = b.T
b

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [ ]:
print(a.shape, b.shape)

(3, 4) (4, 3)


In [ ]:
a @ b

array([[ 20,  44,  68],
       [ 60, 148, 236],
       [100, 252, 404]])

함수 방법으로 np.dot()을 사용할 수 있다.  

In [ ]:
np.dot(a, a.T) #ndarray

array([[ 14,  38,  62],
       [ 38, 126, 214],
       [ 62, 214, 366]])

In [ ]:
b = np.matrix(b)
type(b)

numpy.matrix

In [ ]:
np.dot(b, b.T)

matrix([[107, 122, 137, 152],
        [122, 140, 158, 176],
        [137, 158, 179, 200],
        [152, 176, 200, 224]])

In [ ]:
a.dot(a.T)

array([[ 14,  38,  62],
       [ 38, 126, 214],
       [ 62, 214, 366]])

### brodcasting
python은 배열과 숫자간에 연산을 할 수 있다.  

In [ ]:
[1,2,3] + 1 # 리스트는 계산이 안된다.

TypeError: ignored

In [ ]:
a = np.array([1,2,3]) # 배열로 생성하면
a+1 # 배열안의 데이터를 하나씩 증가시킬 수 있다.

array([2, 3, 4])

broadcasting이란 모양(shape)이 안 맞는데, 특정한 조건에 맞으면 모양을 같게 만들어 연산하는 기능이다.  
위 연산에서 1을 a에 같은 모양으로 만들어 준다.  

연산을 하기 위해서 모양을 변형하는데 배 차이가 안나면 계산이 불가능하다.  

*** shape 모양이 배차이가 나야만 broadcasting이 발생한다.***  

In [ ]:
b = np.arange(6).reshape(2,3)
b # 2행 3열

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
c = np.array([3,4]) # 1행 2열
c

array([3, 4])

### axis
axis는 다차원 배열을 연산할 때 기준이 되는 축이다.  

In [ ]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.sum(a) # 하나로 누적이 된다.

66

(0,0),(0,1),(0,2),(0,3)  
(1,0),(1,1),(1,2),(1,3)  
(2,0),(2,1),(2,2),(2,3)  

In [ ]:
# a 배열은 2차원이므로 axis = 0은 행기준(행마다)
np.sum(a,axis=0) # 2차원 배열에서. 0은 행을 기준으로 누적이 이루어진다.

array([12, 15, 18, 21])

In [ ]:
np.sum(a, axis=1) # a 배열은 2차원이므로 axis =1은 열기준(열마다)

array([ 6, 22, 38])

### 3차원 이상에서 축기준 계산  

In [ ]:
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
np.sum(a, axis=0) # 0 = 같은 형렬 인덱스 번호끼리.. 계산이 된다., 공간기준(공간마다)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [ ]:
np.sum(a, axis=1) #행기준 (행마다),, 한 차원의 행의 합을 구하는듯.. 세로로

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [ ]:
np.sum(a, axis=2) # 열기준 (열마다),, 한 차원의 가로 계산

array([[ 6, 22, 38],
       [54, 70, 86]])

### array 모양 바꾸기

### (1) reshape  
reshape은 차원을 바꿔주는 기능을 한다.  

In [ ]:
a = np.arange(24)
b=a.reshape(3,8)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
a.reshape(2,3,5) # 데이터의 갯수가 30개여야 생성이 가능한데 b의 갯수는 24개임

ValueError: ignored

In [ ]:
# 음수를 쓰면, 알아서 shape을 맞춘다.
a.reshape(2,3,-1) # -1로 된 자리는 나머지로 채워진다.

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
# 음수면 어떤 값을 넣든 상관이 없다.
# 음수이기만 하면 -100도 상관없다.
a.reshape(2,3,-100)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
a.reshape(3,5,-1) #.. 요소의 갯수의 맞처서 숫자에 맞출 수 없음. 
# 음수값은 한번만 사용하며, 사용 위치는 어디든 상관이 없다.
# 고정된 값을 줄 때 배열의 크기를 고려해서 준다.

ValueError: ignored

In [ ]:
# 음수를 2개 사용할 수 없다.
# 음수는 어느 위치에서 사용하든 상관없다 이런건가 사실 놓침
a.reshape(3,-1,-1)

ValueError: ignored

In [ ]:
# 음수값이 1개이면 위치는 어디에 오든 상관없다.

###(2) reshape으로 차원 늘리

In [ ]:
# 1차원 -> 2차원
a=np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
# 1차원 -> 3차원
a=np.arange(6).reshape(1,3,2)
a

array([[[0, 1],
        [2, 3],
        [4, 5]]])

### resize

In [ ]:
# size는 원소 개수를 알려준다.
a = np.arange(24)
print(a.size)
print(len(a))

24
24


In [ ]:
# mutable이다. return이 없고 자기 자신을 바꾼다. -> reshape과 차이점1
# 원래의원소 개수와 변경하는 원소 개수가 안 맞아도 된다. (0으로 채워준다) -> reshpae과 차이점2
b =np.arange(24)
b.resize((2,3,8))
b

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]],

       [[ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0]]])

### array 쪼개기

split

In [ ]:
a = np.arange(24) # 1차원 배열 생성
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
# indices_or_sections
# a =np.split(a,3, axis=0) # 1차원 배열을 하나로 쪼개서 a에 list로 저장을 한다. 각각의 값은 배열임
print(a)
print(type(a))
print(a[0], type(a[0])) # 배열 출력하기

[array([0, 1, 2, 3, 4, 5, 6, 7]), array([ 8,  9, 10, 11, 12, 13, 14, 15]), array([16, 17, 18, 19, 20, 21, 22, 23])]
<class 'list'>
[0 1 2 3 4 5 6 7] <class 'numpy.ndarray'>


hsplit & vsplit

split은 axis 파라미터가 있다. default:axis=0

In [ ]:
a = np.arange(24)
b = a.reshape(4,6)
print(b)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [ ]:
np.split(b, 2)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

In [ ]:
np.split(b,2,axis=0)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

In [ ]:
np.hsplit(a,2) # 호리존탈 스프리트,, 쪼개는 차원이 다름. 1차원해서 가지고 옴

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])]

In [ ]:
np.split(b,2,axis=1) #열을 기준을 쪼개짐

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]]), array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]])]

In [ ]:
np.vsplit(b,2) # 행을 기준으로 쪼개지는건가?

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

In [ ]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
np.hsplit(b,2) # 열단위로 쪼개짐,, 차수가 유지가 됨

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]]), array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]])]

indices_or_sections
- split 시리즈 함수들의 두번째 파라미터 이름이 indices_or_sections이다.
- 숫자를 묶어서 넣으면 구간으로 쪼개진다.

In [ ]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
# section
# 처음부터 ~ 2 미만 : [0,1]
# 2부터 ~ 3 미만 :[2]
# 3부터 ~ 끝까지 : [3,4,5...]
np.hsplit(a, (2,3)) # 2 미만까지.. 2에서 3 미만까지

[array([0, 1]),
 array([2]),
 array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
        20, 21, 22, 23])]

### array 합치기

In [ ]:
a = np.arange(24)
x,y,z = np.split(a, 3)

In [ ]:
print(x)
print(y)
print(z)

[0 1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14 15]
[16 17 18 19 20 21 22 23]


hstack & vstack

In [ ]:
np.hstack((x,y))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
np.vstack((x,y)) 

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

dstack
- dstack은 합쳐서 3차원으로 만들어준다.
- 합칠 array들이 1차원, 2차원일 경우는 차원을 늘린 후 합친다.
- 합쳐지는 차원은 axis=2이다.

In [ ]:
print(x)
print(y)

[0 1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14 15]


In [ ]:

c = np.dstack((x, y))
c

array([[[ 0,  8],
        [ 1,  9],
        [ 2, 10],
        [ 3, 11],
        [ 4, 12],
        [ 5, 13],
        [ 6, 14],
        [ 7, 15]]])

In [ ]:
c.shape #.. 1차원의 갯수(8)

(1, 8, 2)

In [ ]:
x=x.reshape(2,4)
y=y.reshape(2,4)

In [ ]:
print(x)
print(y)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
c =np.dstack((x,y))
c

array([[[ 0,  8],
        [ 1,  9],
        [ 2, 10],
        [ 3, 11]],

       [[ 4, 12],
        [ 5, 13],
        [ 6, 14],
        [ 7, 15]]])

In [ ]:
c.shape # 2차원, 4열 2행이랑 같은 의미인건가?

(2, 4, 2)

### concatenate
concatenate는 axis 방향에 그대로 합쳐진다.
※ stack는 axis 방향에 새로운 차원을 만들어 합쳐준다.

In [ ]:
a =np.arange(12).reshape(3,4)
x,y=np.split(a,2,axis=1)

In [ ]:
print(x)
print(y)

[[0 1]
 [4 5]
 [8 9]]
[[ 2  3]
 [ 6  7]
 [10 11]]


In [ ]:
# 원리 shape 크기 그대로 유지를 한다.
np.concatenate((x,y)) # axis =0 

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [ 2,  3],
       [ 6,  7],
       [10, 11]])

In [ ]:
# shape 크기를 1개 증가해서 합친디다
np.stack((x,y)) # axis =0

array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[ 2,  3],
        [ 6,  7],
        [10, 11]]])

### 차원확장

reshape

In [ ]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

stack

In [ ]:
# 3차원으로 확장
# tuple에 원소가 1개 있으면 차원만 확장시켜 준다.
np.stack((a,)) # 튜플로 넣어주면 차원이 확장된다.

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

newaxis
- 인덱싱할때 np.newaxis를 쓰면 차원을 늘릴 수 있다.

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a.shape

(3, 4)

In [ ]:
a[0]

array([0, 1, 2, 3])

In [ ]:
a[np.newaxis]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

슬라이싱을 할 때 np.newaxis를 쓰면 차원을 늘릴 수 있다.

In [ ]:
a[:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a[np.newaxis,:] # 차원만 늘려준다? (1,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [ ]:
a[:,np.newaxis] #행의 값이 늘어난다. (3, 1, 4)

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

In [ ]:
a[:,np.newaxis].shape

(3, 1, 4)

In [ ]:
a[:,:,np.newaxis] # (3,4,1)

array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]]])

In [ ]:
a[:,:,np.newaxis].shape

(3, 4, 1)

In [ ]:
np.newaxis is None # np.newaixs에 none 값을 넣어도 된다?

True

np.newaxis 대신에 None을 써도 된다.  
None은 직관적이지 않고 엣갈려서 np.newaxis를 만들었다  
numpy를 만들 때 python의 모든 연산자를 다 사용해서 남은 연산자가 없었다.   
그래서 None를 이용했다.

In [ ]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

expand_dims

In [ ]:
np.expand_dims(a,0) # 공간이 하나 추가.. 아마 차원을 말하는 것 같다. 
# a[np.newaxis:,:] 같다

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [ ]:
np.expand_dims(a,1) #a[:,np.newaxis,:] 같다

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

In [ ]:
np.expand_dims(a,2) # a[:,:,np.newaxis]같다

array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]]])

### array 한줄로 펴

flatten

In [ ]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# flatten()은 결과를 return하고 메모리의 값을 변경되지 않는다.
b=a.flatten()
b 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

swapaxes

In [ ]:
a = np.array([[1],[2]]) # 2차원 2행 1열
a

array([[1],
       [2]])

In [ ]:
a.shape

(2, 1)

In [ ]:
# a의 0번 차원과 1번 차원을 서로 바꾼다.
b=np.swapaxes(a,1,0)
b

array([[1, 2]])

In [ ]:
a.T

array([[1, 2]])